remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: Data-Efficient Learning of Natural Language to Linear Temporal Logic Translators for Robot Task Specification
description: "Ziqiao Ma *, Jiayi Pan *, Joyce Chai"
